[project]
name = "kickoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyfiglet>=1.0.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "requests-cache>=1.3.2",
    "textual>=8.2.7",
    "textual-dev>=1.8.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
